services:
  web:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile.server
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - "5001:5001"
